"""customers quotes proformas

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('trade_term', sa.String(length=120), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('default_margin_pct', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('images',
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('media_type', sa.String(length=40), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('offer_no', sa.String(length=60), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parent_quote_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_snapshot', sa.JSON(), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('trade_term', sa.String(length=120), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('notes_header', sa.Text(), nullable=True),
    sa.Column('notes_footer', sa.Text(), nullable=True),
    sa.Column('discount_pct', sa.String(length=32), nullable=True),
    sa.Column('discount_amount', sa.String(length=32), nullable=True),
    sa.Column('subtotal', sa.String(length=32), nullable=False),
    sa.Column('grand_total', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_no', 'revision')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_offer_no'), ['offer_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_status'), ['status'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('proforma_invoices',
    sa.Column('pi_no', sa.String(length=60), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('po_no', sa.String(length=80), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('customer_snapshot', sa.JSON(), nullable=False),
    sa.Column('attention', sa.String(length=120), nullable=True),
    sa.Column('seller_contact', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('foc_pct', sa.String(length=32), nullable=True),
    sa.Column('freight', sa.String(length=32), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.String(length=32), nullable=False),
    sa.Column('total', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('revised_from_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revised_from_id'], ['proforma_invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_no')
    )
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_invoices_quote_id'), ['quote_id'], unique=False)

    op.create_table('quote_sections',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('layout', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_sections_quote_id'), ['quote_id'], unique=False)

    op.create_table('quote_lines',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_emphasis', sa.Boolean(), nullable=False),
    sa.Column('description_lines', sa.JSON(), nullable=False),
    sa.Column('model_no', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('image_ids', sa.JSON(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.String(length=32), nullable=True),
    sa.Column('margin_pct', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.String(length=32), nullable=False),
    sa.Column('unit_price_manual', sa.Boolean(), nullable=False),
    sa.Column('total', sa.String(length=32), nullable=False),
    sa.Column('price_source', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['quote_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quote_lines_section_id'), ['section_id'], unique=False)

    op.create_table('proforma_lines',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('source_line_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('model_no', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description_lines', sa.JSON(), nullable=False),
    sa.Column('image_ids', sa.JSON(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.String(length=32), nullable=False),
    sa.Column('total', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['proforma_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_line_id'], ['quote_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proforma_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_lines_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('material')
        batch_op.drop_column('model_no')

    with op.batch_alter_table('proforma_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_lines_invoice_id'))

    op.drop_table('proforma_lines')
    with op.batch_alter_table('quote_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_lines_section_id'))
        batch_op.drop_index(batch_op.f('ix_quote_lines_product_id'))

    op.drop_table('quote_lines')
    with op.batch_alter_table('quote_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_sections_quote_id'))

    op.drop_table('quote_sections')
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_quote_id'))

    op.drop_table('proforma_invoices')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_quotes_offer_no'))
        batch_op.drop_index(batch_op.f('ix_quotes_customer_id'))

    op.drop_table('quotes')
    op.drop_table('images')
    op.drop_table('customers')
    # ### end Alembic commands ###
