"""configurations

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_zh", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("platform", sa.String(length=120), nullable=True),
        sa.Column("model_no", sa.String(length=120), nullable=True),
        sa.Column("material", sa.String(length=120), nullable=True),
        sa.Column("base_margin_pct", sa.String(length=32), nullable=True),
        sa.Column("image_ids", sa.JSON(), nullable=False),
        sa.Column("saved_cost", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "configuration_items",
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("cost_usd", sa.String(length=32), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=10), nullable=True),
        sa.Column("emphasis", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["configuration_id"], ["configurations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("configuration_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_configuration_items_configuration_id"),
            ["configuration_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_configuration_items_product_id"), ["product_id"], unique=False
        )

    # plain ADD COLUMN, no rebuild of quote_lines (see 0003 and alembic/env.py)
    op.execute(
        "ALTER TABLE quote_lines ADD COLUMN configuration_id INTEGER "
        "REFERENCES configurations (id) ON DELETE SET NULL"
    )
    op.create_index("ix_quote_lines_configuration_id", "quote_lines", ["configuration_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quote_lines_configuration_id", "quote_lines")
    op.drop_column("quote_lines", "configuration_id")

    with op.batch_alter_table("configuration_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_items_product_id"))
        batch_op.drop_index(batch_op.f("ix_configuration_items_configuration_id"))

    op.drop_table("configuration_items")
    op.drop_table("configurations")
    # ### end Alembic commands ###
